site_name: devpogi readings
site_author: devprabal

nav:
  - Readings: index.md

theme:
  name: material
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      accent: default
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: default
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: Nunito
    code: JetBrains Mono
  icon:
    logo: material/book
    admonition:
      abstract: material/chart-timeline-variant-shimmer
  features:
    - navigation.top
    - search.highlight
    - navigation.instant

extra_css:
  - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition

plugins:
  - social