site_name: devpogi readings
site_author: devpogi
site_url: https://devprabal.github.io/readings
site_description: devpogi's thoughts on books, articles, talks and media  

nav:
  - articles: articles.md
  - books: books.md
  - videos: videos.md

not_in_nav: |
  /index.md

# theme:
#   name: material
#   palette:
#     - media: "(prefers-color-scheme: light)"
#       scheme: default
#       primary: white
#       accent: default
#       toggle:
#         icon: material/toggle-switch-off-outline
#         name: Switch to dark mode
#     - media: "(prefers-color-scheme: dark)"
#       scheme: slate
#       primary: black
#       accent: default
#       toggle:
#         icon: material/toggle-switch
#         name: Switch to light mode
#   font:
#     text: Nunito
#     code: JetBrains Mono
#   icon:
#     logo: material/book
#     admonition:
#       abstract: material/chart-timeline-variant-shimmer
#   features:
#     - navigation.top
#     - search.highlight
#     - navigation.instant

## [swan theme](https://github.com/swan-cern/mkdocs-swan)
# theme:
#   name: 'swan'

### [cluster theme](https://pythonhosted.org/mkdocs-cluster/)
# theme:
#   name: cluster

# ### [walt theme](https://github.com/codesue/walt)
# theme:
#   name: walt

# ### [alabaster theme](https://github.com/notpushkin/mkdocs-alabaster)
# theme:
#   name: alabaster

# theme: 
#   name: readthedocs

# ### [simple-blog theme](https://github.com/FernandoCelmer/mkdocs-simple-blog)
# theme:
#   name: simple-blog
#   title_style: overline
#   site_name_style: bold
#   theme_style: light #dark
#   components:
#     site_name: true
#     footer: false
#     sidebar: true
#     navigation_depth: 2
#     preview: false ## disables Next and Prev in footer

theme:
  name: mkdocs
  color_mode: auto
  user_color_mode_toggle: true
  nav_style: dark
  shortcuts:
    search: 83   # s

# theme:
#   name: shadcn
#   show_title: true
#   icon: ci:bookmark ## https://icon-sets.iconify.design/ci/?icon-filter=book


# theme:
#   name: terminal

# extra_css:
#   - stylesheets/extra.css

markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.details
  - admonition

plugins:
  - search
  # - social ## needs theme: material-for-mkdocs

validation:
  omitted_files: warn
  absolute_links: warn
  unrecognized_links: warn
